[package]
name = "ferrimoji"
version = "0.1.0"
authors = ["LevitatingBusinessMan <public@reinfernhout.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libvips = "1.4.2"
anyhow = "1.0.40"
